/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.util.InputMismatchException;

import javax.swing.JOptionPane;

/**
 *
 * @author n_cheluv
 */
public class StdDevGui extends javax.swing.JFrame {

  /**
     * Creates new form StdDevGUI.
     */
  public StdDevGui() {
    initComponents();
  }
  
  StandardDeviation stdDev = new StandardDeviation();
  
  /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    buttonGroup1 = new javax.swing.ButtonGroup();
    jscrollPane1 = new javax.swing.JScrollPane();
    inputTextField = new javax.swing.JTextArea();
    calculateButton = new javax.swing.JButton();
    sampleRadioButon = new javax.swing.JRadioButton();
    populationRadioButton = new javax.swing.JRadioButton();
    clearButton = new javax.swing.JButton();
    welcomeLabel = new javax.swing.JLabel();
    inputMessageLabel = new javax.swing.JLabel();
    resultLabel = new javax.swing.JLabel();
    jlabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setBackground(new java.awt.Color(220, 220, 220));

    inputTextField.setColumns(20);
    inputTextField.setRows(5);
    jscrollPane1.setViewportView(inputTextField);

    calculateButton.setText("Calculate");
    calculateButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        calculateButtonActionPerformed(evt);
        }
        });

    buttonGroup1.add(sampleRadioButon);
    sampleRadioButon.setText("Sample SD");

    buttonGroup1.add(populationRadioButton);
    populationRadioButton.setText("Population SD");

    clearButton.setText("Clear");
    clearButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        clearButtonActionPerformed(evt);
        }
        });

    welcomeLabel.setText("***** WELCOME TO CALCULATOR STANDARD DEVIATION FUNCTION*****");

    inputMessageLabel.setText(" NOTE:Please enter two or more input providing one space after each value");

    resultLabel.setText("    ");

    jlabel1.setText("RESULT : ");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(populationRadioButton)
                        .addGap(64, 64, 64)
                        .addComponent(sampleRadioButon))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 
                         102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE,
                          83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(inputMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 
                        419, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, 
                     layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jscrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                         428, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(welcomeLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlabel1)
                .addGap(52, 52, 52)
                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 
                 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 
                 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputMessageLabel)
                .addGap(9, 9, 9)
                .addComponent(jscrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 
                 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(populationRadioButton)
                    .addComponent(sampleRadioButon))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE,
                     33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 
                     33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE,
                     30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel1))
                .addContainerGap(48, Short.MAX_VALUE))
    );

    pack();
  } // </editor-fold>                        

  private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
    // TODO add your handling code here:
        
    String value = inputTextField.getText();
    double [] vals = {};
        
    if (!value.trim().equals("") && (sampleRadioButon.isSelected()  
        || populationRadioButton.isSelected())) {
      //resultLabel.setText(value);
      String[] array = (value.split(" "));
      vals = new double[array.length];
      try {
        if (array.length >= 2) {
          for (int i = 0;i < array.length;i++) {
            vals[i] = Double.parseDouble(array[i]);
          }
        }
        else if ((array.length == 0)||(array == null)) {
          JOptionPane.showMessageDialog(null, "Error occured: No inputs given");
        }
        else {
          JOptionPane.showMessageDialog(null, "Error Occured:only one value Identified, Please check NOTE");
        }
      }
      catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Error Parsing Values please Enter valid numbers");
        clearButton.doClick();
      }
      catch (InputMismatchException e) {
        JOptionPane.showMessageDialog(null, "Error Parsing Values Please Enter a valid Number");
        clearButton.doClick();
      }
    }
    if ((sampleRadioButon.isSelected())&&(vals.length >= 2)) {
      final double stdDev1 = stdDev.calculateSampleStdDev(vals);
      String result1 = String.valueOf(stdDev1);
      resultLabel.setText(result1);
    }
    else if ((populationRadioButton.isSelected())&&(vals.length >= 2)) {
      final double stdDev1 = stdDev.calculatePopulationStdDev(vals);
      String result1 = String.valueOf(stdDev1);
      resultLabel.setText(result1);
    }
  }                                               

  private void clearButtonActionPerformed (java.awt.event.ActionEvent evt) {                                            
    // TODO add your handling code here:
    inputTextField.setText("");
    buttonGroup1.clearSelection();
    resultLabel.setText("");
  }                                           

  /**
     * @param args the command line arguments.
     */
  public static void main(String[] args) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available,
         *  stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : 
          javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(StdDevGui.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(StdDevGui.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(StdDevGui.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(StdDevGui.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /**
    *Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new StdDevGui().setVisible(true);
      }
        });
  }

  // Variables declaration - do not modify                     
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JButton calculateButton;
  private javax.swing.JButton clearButton;
  private javax.swing.JLabel inputMessageLabel;
  private javax.swing.JTextArea inputTextField;
  private javax.swing.JLabel jlabel1;
  private javax.swing.JScrollPane jscrollPane1;
  private javax.swing.JRadioButton populationRadioButton;
  private javax.swing.JLabel resultLabel;
  private javax.swing.JRadioButton sampleRadioButon;
  private javax.swing.JLabel welcomeLabel;
  // End of variables declaration                   
}

